CFLAGS += -fPIC

all: libmylib.so.1

main: main.o libmylib.so libmylib.so.1 libmylib.so.1.0.0

libmylib.so: libmylib.so.1.0.0
	ln -sf libmylib.so.1.0.0 libmylib.so

libmylib.so.1: libmylib.so.1.0.0
	ln -sf libmylib.so.1.0.0 libmylib.so.1

libmylib.so.1.0.0: mylib.o
	$(CC) -shared -Wl,-soname,libmylib.so.1 $(CFLAGS) $(LDFLAGS) -o$@ $< $(LDLIBS)
